baseURL = "https://mirischia.github.io"
defaultContentLanguage = "en"
languageCode = "en"
title = "Mirischia"
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

pygmentsStyle = "dracula"

[params]
  avatarURL = "/images/avatar.png"
  avatarSize = "size-xl"
  avatarAltText = "avatar"
  footer = "Mirischia"
  description = ""
  showPostsOnHomePage = "recent"
  customHeadHTML = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
